/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MisAnunciosRouteImport } from './routes/mis-anuncios'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RestablecerRouteImport } from './routes/restablecer'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnunciosRouteImport } from './routes/admin/anuncios'
import { Route as AdminContactosRouteImport } from './routes/admin/contactos'
import { Route as AdminOfertasRouteImport } from './routes/admin/ofertas'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminVerificacionesRouteImport } from './routes/admin/verificaciones'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiFavoritesRouteImport } from './routes/api/favorites'
import { Route as ApiFeaturedRouteImport } from './routes/api/featured'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiMyVehiclesRouteImport } from './routes/api/my-vehicles'
import { Route as ApiOffersRouteImport } from './routes/api/offers'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiVehiclesRouteImport } from './routes/api/vehicles'
import { Route as VehiculoIdRouteImport } from './routes/vehiculo.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMyVehiclesIdRouteImport } from './routes/api/my-vehicles.$id'
import { Route as ApiOffersIdRouteImport } from './routes/api/offers.$id'
import { Route as ApiVehiclesIdRouteImport } from './routes/api/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MisAnunciosRoute = MisAnunciosRouteImport.update({
  id: '/mis-anuncios',
  path: '/mis-anuncios',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RestablecerRoute = RestablecerRouteImport.update({
  id: '/restablecer',
  path: '/restablecer',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnunciosRoute = AdminAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactosRoute = AdminContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOfertasRoute = AdminOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificacionesRoute = AdminVerificacionesRouteImport.update({
  id: '/verificaciones',
  path: '/verificaciones',
  getParentRoute: () => AdminRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFavoritesRoute = ApiFavoritesRouteImport.update({
  id: '/api/favorites',
  path: '/api/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeaturedRoute = ApiFeaturedRouteImport.update({
  id: '/api/featured',
  path: '/api/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyVehiclesRoute = ApiMyVehiclesRouteImport.update({
  id: '/api/my-vehicles',
  path: '/api/my-vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOffersRoute = ApiOffersRouteImport.update({
  id: '/api/offers',
  path: '/api/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVehiclesRoute = ApiVehiclesRouteImport.update({
  id: '/api/vehicles',
  path: '/api/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculoIdRoute = VehiculoIdRouteImport.update({
  id: '/vehiculo/$id',
  path: '/vehiculo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMyVehiclesIdRoute = ApiMyVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiMyVehiclesRoute,
} as any)
const ApiOffersIdRoute = ApiOffersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiOffersRoute,
} as any)
const ApiVehiclesIdRoute = ApiVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiVehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mis-anuncios': typeof MisAnunciosRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/recuperar': typeof RecuperarRoute
  '/restablecer': typeof RestablecerRoute
  '/terminos': typeof TerminosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/featured': typeof ApiFeaturedRoute
  '/api/me': typeof ApiMeRoute
  '/api/my-vehicles': typeof ApiMyVehiclesRouteWithChildren
  '/api/offers': typeof ApiOffersRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/vehiculo/$id': typeof VehiculoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/my-vehicles/$id': typeof ApiMyVehiclesIdRoute
  '/api/offers/$id': typeof ApiOffersIdRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mis-anuncios': typeof MisAnunciosRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/recuperar': typeof RecuperarRoute
  '/restablecer': typeof RestablecerRoute
  '/terminos': typeof TerminosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/featured': typeof ApiFeaturedRoute
  '/api/me': typeof ApiMeRoute
  '/api/my-vehicles': typeof ApiMyVehiclesRouteWithChildren
  '/api/offers': typeof ApiOffersRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/vehiculo/$id': typeof VehiculoIdRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/my-vehicles/$id': typeof ApiMyVehiclesIdRoute
  '/api/offers/$id': typeof ApiOffersIdRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mis-anuncios': typeof MisAnunciosRoute
  '/ofertas': typeof OfertasRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/recuperar': typeof RecuperarRoute
  '/restablecer': typeof RestablecerRoute
  '/terminos': typeof TerminosRoute
  '/admin/anuncios': typeof AdminAnunciosRoute
  '/admin/contactos': typeof AdminContactosRoute
  '/admin/ofertas': typeof AdminOfertasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/verificaciones': typeof AdminVerificacionesRoute
  '/api/contact': typeof ApiContactRoute
  '/api/favorites': typeof ApiFavoritesRoute
  '/api/featured': typeof ApiFeaturedRoute
  '/api/me': typeof ApiMeRoute
  '/api/my-vehicles': typeof ApiMyVehiclesRouteWithChildren
  '/api/offers': typeof ApiOffersRouteWithChildren
  '/api/profile': typeof ApiProfileRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/vehicles': typeof ApiVehiclesRouteWithChildren
  '/vehiculo/$id': typeof VehiculoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/my-vehicles/$id': typeof ApiMyVehiclesIdRoute
  '/api/offers/$id': typeof ApiOffersIdRoute
  '/api/vehicles/$id': typeof ApiVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/mis-anuncios'
    | '/ofertas'
    | '/perfil'
    | '/publicar'
    | '/recuperar'
    | '/restablecer'
    | '/terminos'
    | '/admin/anuncios'
    | '/admin/contactos'
    | '/admin/ofertas'
    | '/admin/usuarios'
    | '/admin/verificaciones'
    | '/api/contact'
    | '/api/favorites'
    | '/api/featured'
    | '/api/me'
    | '/api/my-vehicles'
    | '/api/offers'
    | '/api/profile'
    | '/api/stats'
    | '/api/vehicles'
    | '/vehiculo/$id'
    | '/admin/'
    | '/api/auth/$'
    | '/api/my-vehicles/$id'
    | '/api/offers/$id'
    | '/api/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/mis-anuncios'
    | '/ofertas'
    | '/perfil'
    | '/publicar'
    | '/recuperar'
    | '/restablecer'
    | '/terminos'
    | '/admin/anuncios'
    | '/admin/contactos'
    | '/admin/ofertas'
    | '/admin/usuarios'
    | '/admin/verificaciones'
    | '/api/contact'
    | '/api/favorites'
    | '/api/featured'
    | '/api/me'
    | '/api/my-vehicles'
    | '/api/offers'
    | '/api/profile'
    | '/api/stats'
    | '/api/vehicles'
    | '/vehiculo/$id'
    | '/admin'
    | '/api/auth/$'
    | '/api/my-vehicles/$id'
    | '/api/offers/$id'
    | '/api/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/mis-anuncios'
    | '/ofertas'
    | '/perfil'
    | '/publicar'
    | '/recuperar'
    | '/restablecer'
    | '/terminos'
    | '/admin/anuncios'
    | '/admin/contactos'
    | '/admin/ofertas'
    | '/admin/usuarios'
    | '/admin/verificaciones'
    | '/api/contact'
    | '/api/favorites'
    | '/api/featured'
    | '/api/me'
    | '/api/my-vehicles'
    | '/api/offers'
    | '/api/profile'
    | '/api/stats'
    | '/api/vehicles'
    | '/vehiculo/$id'
    | '/admin/'
    | '/api/auth/$'
    | '/api/my-vehicles/$id'
    | '/api/offers/$id'
    | '/api/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ContactoRoute: typeof ContactoRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MisAnunciosRoute: typeof MisAnunciosRoute
  OfertasRoute: typeof OfertasRoute
  PerfilRoute: typeof PerfilRoute
  PublicarRoute: typeof PublicarRoute
  RecuperarRoute: typeof RecuperarRoute
  RestablecerRoute: typeof RestablecerRoute
  TerminosRoute: typeof TerminosRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiFavoritesRoute: typeof ApiFavoritesRoute
  ApiFeaturedRoute: typeof ApiFeaturedRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiMyVehiclesRoute: typeof ApiMyVehiclesRouteWithChildren
  ApiOffersRoute: typeof ApiOffersRouteWithChildren
  ApiProfileRoute: typeof ApiProfileRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiVehiclesRoute: typeof ApiVehiclesRouteWithChildren
  VehiculoIdRoute: typeof VehiculoIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-anuncios': {
      id: '/mis-anuncios'
      path: '/mis-anuncios'
      fullPath: '/mis-anuncios'
      preLoaderRoute: typeof MisAnunciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restablecer': {
      id: '/restablecer'
      path: '/restablecer'
      fullPath: '/restablecer'
      preLoaderRoute: typeof RestablecerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anuncios': {
      id: '/admin/anuncios'
      path: '/anuncios'
      fullPath: '/admin/anuncios'
      preLoaderRoute: typeof AdminAnunciosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contactos': {
      id: '/admin/contactos'
      path: '/contactos'
      fullPath: '/admin/contactos'
      preLoaderRoute: typeof AdminContactosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ofertas': {
      id: '/admin/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AdminOfertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verificaciones': {
      id: '/admin/verificaciones'
      path: '/verificaciones'
      fullPath: '/admin/verificaciones'
      preLoaderRoute: typeof AdminVerificacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/favorites': {
      id: '/api/favorites'
      path: '/api/favorites'
      fullPath: '/api/favorites'
      preLoaderRoute: typeof ApiFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/featured': {
      id: '/api/featured'
      path: '/api/featured'
      fullPath: '/api/featured'
      preLoaderRoute: typeof ApiFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-vehicles': {
      id: '/api/my-vehicles'
      path: '/api/my-vehicles'
      fullPath: '/api/my-vehicles'
      preLoaderRoute: typeof ApiMyVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/offers': {
      id: '/api/offers'
      path: '/api/offers'
      fullPath: '/api/offers'
      preLoaderRoute: typeof ApiOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vehicles': {
      id: '/api/vehicles'
      path: '/api/vehicles'
      fullPath: '/api/vehicles'
      preLoaderRoute: typeof ApiVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehiculo/$id': {
      id: '/vehiculo/$id'
      path: '/vehiculo/$id'
      fullPath: '/vehiculo/$id'
      preLoaderRoute: typeof VehiculoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/my-vehicles/$id': {
      id: '/api/my-vehicles/$id'
      path: '/$id'
      fullPath: '/api/my-vehicles/$id'
      preLoaderRoute: typeof ApiMyVehiclesIdRouteImport
      parentRoute: typeof ApiMyVehiclesRoute
    }
    '/api/offers/$id': {
      id: '/api/offers/$id'
      path: '/$id'
      fullPath: '/api/offers/$id'
      preLoaderRoute: typeof ApiOffersIdRouteImport
      parentRoute: typeof ApiOffersRoute
    }
    '/api/vehicles/$id': {
      id: '/api/vehicles/$id'
      path: '/$id'
      fullPath: '/api/vehicles/$id'
      preLoaderRoute: typeof ApiVehiclesIdRouteImport
      parentRoute: typeof ApiVehiclesRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnunciosRoute: typeof AdminAnunciosRoute
  AdminContactosRoute: typeof AdminContactosRoute
  AdminOfertasRoute: typeof AdminOfertasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVerificacionesRoute: typeof AdminVerificacionesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnunciosRoute: AdminAnunciosRoute,
  AdminContactosRoute: AdminContactosRoute,
  AdminOfertasRoute: AdminOfertasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVerificacionesRoute: AdminVerificacionesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiMyVehiclesRouteChildren {
  ApiMyVehiclesIdRoute: typeof ApiMyVehiclesIdRoute
}

const ApiMyVehiclesRouteChildren: ApiMyVehiclesRouteChildren = {
  ApiMyVehiclesIdRoute: ApiMyVehiclesIdRoute,
}

const ApiMyVehiclesRouteWithChildren = ApiMyVehiclesRoute._addFileChildren(
  ApiMyVehiclesRouteChildren,
)

interface ApiOffersRouteChildren {
  ApiOffersIdRoute: typeof ApiOffersIdRoute
}

const ApiOffersRouteChildren: ApiOffersRouteChildren = {
  ApiOffersIdRoute: ApiOffersIdRoute,
}

const ApiOffersRouteWithChildren = ApiOffersRoute._addFileChildren(
  ApiOffersRouteChildren,
)

interface ApiVehiclesRouteChildren {
  ApiVehiclesIdRoute: typeof ApiVehiclesIdRoute
}

const ApiVehiclesRouteChildren: ApiVehiclesRouteChildren = {
  ApiVehiclesIdRoute: ApiVehiclesIdRoute,
}

const ApiVehiclesRouteWithChildren = ApiVehiclesRoute._addFileChildren(
  ApiVehiclesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ContactoRoute: ContactoRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MisAnunciosRoute: MisAnunciosRoute,
  OfertasRoute: OfertasRoute,
  PerfilRoute: PerfilRoute,
  PublicarRoute: PublicarRoute,
  RecuperarRoute: RecuperarRoute,
  RestablecerRoute: RestablecerRoute,
  TerminosRoute: TerminosRoute,
  ApiContactRoute: ApiContactRoute,
  ApiFavoritesRoute: ApiFavoritesRoute,
  ApiFeaturedRoute: ApiFeaturedRoute,
  ApiMeRoute: ApiMeRoute,
  ApiMyVehiclesRoute: ApiMyVehiclesRouteWithChildren,
  ApiOffersRoute: ApiOffersRouteWithChildren,
  ApiProfileRoute: ApiProfileRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiVehiclesRoute: ApiVehiclesRouteWithChildren,
  VehiculoIdRoute: VehiculoIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
